version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      - QDRANT__SERVICE__GRPC_PORT=6334
    networks:
      - face-net

  face-api:
    build: .
    depends_on:
      - qdrant
    environment:
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - COLLECTION_NAME=face_embeddings
    volumes:
      - ./app:/app/app
    networks:
      - face-net
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "443:443"
    restart: unless-stopped
    volumes:
      # Nginx configuration
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      # certificates
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - face-api
    networks:
      - face-net

volumes:
  qdrant_data:

networks:
  face-net:
    driver: bridge